# https://taskfile.dev

version: '3'

vars:
  BOT_COPIES: "bot_copies"

tasks:
  backup:
    cmds:
      - mkdir -p  {{.BOT_COPIES}}/{{.CLI_ARGS}}
      - cp -r src/* {{.BOT_COPIES}}/{{.CLI_ARGS}}

  submission:
    cmds:
      - tar -vc --directory=./src --exclude-ignore=../.gitignore --exclude-vcs --exclude submission.tar.gz --exclude Taskfile.yaml -zf submission.tar.gz .

  run:
    variables:
      AGAINST: "v0_orig"
    cmds:
      - luxai-s2 src/main.py bot_copies/{{.AGAINST}}/main.py -v 2 -s 101 -o replay.html >log.log

  run-many:
    variables:
      AGAINST: "v0_orig"
    cmds:
      - rm result.csv replays/* || true
      - cd tools/luxai_s2_ab && python ./run_ab.py --agent-a ../../src/main.py --agent-b ../../bot_copies/{{.AGAINST}}/main.py --workdir ../..
      - python -c 'import pandas as pd; print(pd.read_csv("result.csv")["a_win_flag"].mean())'
